using System;
using AssistenciaTech.Models;
using AssistenciaTech.Services;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Moq;
using QuestPDF.Infrastructure;
using Xunit;

namespace AssistenciaTech.Application.Tests.Services
{
    public class PdfGeneratorServiceTests
    {
        private readonly Mock<IHttpContextAccessor> _mockHttpContextAccessor;
        private readonly PdfGeneratorService _service;

        public PdfGeneratorServiceTests()
        {
            _mockHttpContextAccessor = new Mock<IHttpContextAccessor>();
            _service = new PdfGeneratorService(_mockHttpContextAccessor.Object);

            // Required by QuestPDF 2022.12.x and newer
            QuestPDF.Settings.License = LicenseType.Community;
        }

        [Fact]
        public void GenerateOsPdf_NullOrdemServico_ThrowsArgumentNullException()
        {
            // Arrange
#pragma warning disable CS8604 // Possible null reference argument.
            OrdemServico os = null;

            // Act
            Action act = () => _service.GenerateOsPdf(os);
#pragma warning restore CS8604 // Possible null reference argument.

            // Assert
            act.Should().Throw<ArgumentNullException>().WithMessage("*os*");
        }

        [Fact]
        public void GenerateOsPdf_ValidOrdemServico_ReturnsPdfByteArray()
        {
            // Arrange
            var os = new OrdemServico
            {
                Id = 1,
                Equipamento = "Notebook Dell",
                // DefeitoRelatado = "Não liga",
                CustoMaoDeObra = 150m,
                CustoPecas = 0m,
                ClienteId = 1,
                Cliente = new Cliente { Id = 1, Nome = "João Silva", Cpf = "12345678901", Telefone = "11999999999" }
            };

            // Act
            var result = _service.GenerateOsPdf(os);

            // Assert
            result.Should().NotBeNull();
            result.Should().NotBeEmpty();
            // A valid PDF generated by QuestPDF should start with "%PDF-"
            result.Take(5).Should().BeEquivalentTo(new byte[] { 37, 80, 68, 70, 45 });
        }

        [Fact]
        public void GenerateReciboPagamentoPdf_NullFaturamento_ThrowsArgumentNullException()
        {
            // Arrange
#pragma warning disable CS8604 // Possible null reference argument.
            Faturamento faturamento = null;

            // Act
            Action act = () => _service.GenerateReciboPagamentoPdf(faturamento);
#pragma warning restore CS8604 // Possible null reference argument.

            // Assert
            act.Should().Throw<ArgumentNullException>().WithMessage("*faturamento*");
        }

        [Fact]
        public void GenerateReciboPagamentoPdf_NullOrdemServico_ThrowsArgumentNullException()
        {
            // Arrange
            var faturamento = new Faturamento
            {
                Id = 1,
                OrdemServicoId = 1,
#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type.
                OrdemServico = null
#pragma warning restore CS8625 // Cannot convert null literal to non-nullable reference type.
            };

            // Act
            Action act = () => _service.GenerateReciboPagamentoPdf(faturamento);

            // Assert
            act.Should().Throw<ArgumentNullException>().WithMessage("*OrdemServico*");
        }

        [Fact]
        public void GenerateReciboPagamentoPdf_NullCliente_ThrowsArgumentNullException()
        {
            // Arrange
            var os = new OrdemServico
            {
                Id = 1,
                Equipamento = "Notebook Dell",
#pragma warning disable CS8625 // Cannot convert null literal to non-nullable reference type.
                Cliente = null
#pragma warning restore CS8625 // Cannot convert null literal to non-nullable reference type.
            };

            var faturamento = new Faturamento
            {
                Id = 1,
                OrdemServicoId = 1,
                OrdemServico = os
            };

            // Act
            Action act = () => _service.GenerateReciboPagamentoPdf(faturamento);

            // Assert
            act.Should().Throw<ArgumentNullException>().WithMessage("*Cliente*");
        }

        [Fact]
        public void GenerateReciboPagamentoPdf_ValidFaturamento_ReturnsPdfByteArray()
        {
            // Arrange
            var os = new OrdemServico
            {
                Id = 1,
                Equipamento = "Notebook Dell",
                CustoMaoDeObra = 150m,
                CustoPecas = 0m,
                ClienteId = 1,
                Cliente = new Cliente { Id = 1, Nome = "João Silva", Cpf = "12345678901", Telefone = "11999999999" }
            };
            var faturamento = new Faturamento
            {
                Id = 1,
                OrdemServicoId = 1,
                OrdemServico = os,
                ValorTotal = 150m,
                // DataPagamento = DateTime.Now
            };

            // Act
            var result = _service.GenerateReciboPagamentoPdf(faturamento);

            // Assert
            result.Should().NotBeNull();
            result.Should().NotBeEmpty();
            // A valid PDF generated by QuestPDF should start with "%PDF-"
            result.Take(5).Should().BeEquivalentTo(new byte[] { 37, 80, 68, 70, 45 });
        }
    }
}
