using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using AssistenciaTech.Data;

using Npgsql;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();

// Registrando o contexto do banco de dados PostgreSQL
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

// Força a resolução do Host para IPv4 para evitar falhas de IPv6 no Render
if (!string.IsNullOrEmpty(connectionString))
{
    try
    {
        var connBuilder = new NpgsqlConnectionStringBuilder(connectionString);

        // Supabase IPv4 Pooler Rewrite (Supabase removed IPv4 from db.*.supabase.co)
        if (!string.IsNullOrEmpty(connBuilder.Host) && (connBuilder.Host.StartsWith("db.") && connBuilder.Host.EndsWith(".supabase.co") || connBuilder.Host.Contains("pooler.supabase.com")))
        {
            // Parse project ref if it's db.*
            string projectRef = "plygtwevgiziaznttnwc"; // default based on instructions

            if (connBuilder.Host.StartsWith("db.")) {
                var parts = connBuilder.Host.Split('.');
                if (parts.Length >= 2) {
                    projectRef = parts[1];
                }
            }

            // The user has project plygtwevgiziaznttnwc in us-east-1
            string region = "us-east-1";
            if (projectRef == "kpturmbeavfmudrtomea") region = "sa-east-1";

            connBuilder.Host = $"aws-0-{region}.pooler.supabase.com";
            connBuilder.Port = 5432; // Pooler session port (fixes port 6543 issue)

            if (!string.IsNullOrEmpty(connBuilder.Username))
            {
                // Ensure username doesn't already have projectRef
                var baseUsername = connBuilder.Username.Contains(".") ? connBuilder.Username.Split('.')[0] : connBuilder.Username;
                connBuilder.Username = $"{baseUsername}.{projectRef}";
            }

            connBuilder.SslMode = SslMode.Require;
            connBuilder.TrustServerCertificate = true;

            Console.WriteLine($"[Supabase] Rewrote connection string to use IPv4 Pooler: {connBuilder.Host} for user {connBuilder.Username} on port {connBuilder.Port}");
            connectionString = connBuilder.ConnectionString;
        }
        else if (!string.IsNullOrEmpty(connBuilder.Host) && !System.Net.IPAddress.TryParse(connBuilder.Host, out _))
        {
            var addresses = System.Net.Dns.GetHostAddresses(connBuilder.Host);
            var ipv4 = addresses.FirstOrDefault(a => a.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork);
            if (ipv4 != null)
            {
                Console.WriteLine($"[DNS] Resolvendo {connBuilder.Host} para IPv4: {ipv4}");
                connBuilder.Host = ipv4.ToString();
                connectionString = connBuilder.ConnectionString;
            }
        }
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[DNS] Erro ao resolver host para IPv4: {ex.Message}");
    }
}

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(connectionString));

// Configuração do Data Protection (Persistindo chaves no banco de dados para suportar reinícios do contêiner)
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>();

// Configuração de Autenticação baseada em Cookies
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Account/Login";
        options.AccessDeniedPath = "/Account/AccessDenied";
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
    });

// Configuração da Licença do QuestPDF
QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;


// Configuração para proxy reverso (Render, Heroku, etc.)
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

var app = builder.Build();

app.UseForwardedHeaders(); // Movido para o topo do pipeline

// === ADICIONADO: Auto-Migration para produção/Docker ===
// Garante que o banco de dados seja criado e atualizado automaticamente ao iniciar a aplicação.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<AppDbContext>();
        // Cria as tabelas do banco automaticamente sem precisar da pasta Migrations
        context.Database.EnsureCreated();

        // Garante que a tabela de chaves de proteção exista, pois o EnsureCreated ignora se o banco já existir
        context.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""DataProtectionKeys"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""FriendlyName"" text NULL,
                ""Xml"" text NULL,
                CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
            );
        ");
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Ocorreu um erro ao aplicar as migrations do banco de dados.");
    }
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}


app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

// Middlewares de Segurança
app.UseAuthentication();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
