using Microsoft.AspNetCore.HttpOverrides;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using AssistenciaTech.Data;
using AssistenciaTech.Services;

using Npgsql;

// Fix para erro de timezone no PostgreSQL ("Cannot write DateTime with Kind=Local")
AppContext.SetSwitch("Npgsql.EnableLegacyTimestampBehavior", true);

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.
builder.Services.AddControllersWithViews();
builder.Services.AddScoped<IEstoqueService, EstoqueService>();

// Registrando o contexto do banco de dados PostgreSQL
var connectionString = builder.Configuration.GetConnectionString("DefaultConnection");

if (!string.IsNullOrEmpty(connectionString) && (connectionString.StartsWith("postgres://") || connectionString.StartsWith("postgresql://")))
{
    try
    {
        var uri = new Uri(connectionString);
        var userInfo = uri.UserInfo.Split(':');
        var connBuilder = new NpgsqlConnectionStringBuilder
        {
            Host = uri.Host,
            Port = uri.Port > 0 ? uri.Port : 5432,
            Username = userInfo[0],
            Password = userInfo.Length > 1 ? userInfo[1] : "",
            Database = uri.LocalPath.TrimStart('/')
        };
        
        if (connectionString.Contains("sslmode=require", StringComparison.OrdinalIgnoreCase))
        {
            connBuilder.SslMode = SslMode.Require;
            connBuilder.TrustServerCertificate = true;
        }
        
        connectionString = connBuilder.ConnectionString;
        Console.WriteLine($"[Neon/Postgres] Converted URI to connection string for Host: {connBuilder.Host}");
    }
    catch (Exception ex)
    {
        Console.WriteLine($"[Neon/Postgres] Error parsing URI connection string: {ex.Message}");
    }
}

builder.Services.AddDbContext<AppDbContext>(options =>
    options.UseNpgsql(connectionString));

// Configuração do Data Protection (Persistindo chaves no banco de dados para suportar reinícios do contêiner)
builder.Services.AddDataProtection()
    .PersistKeysToDbContext<AppDbContext>();

// Configuração de Autenticação baseada em Cookies
builder.Services.AddAuthentication(CookieAuthenticationDefaults.AuthenticationScheme)
    .AddCookie(options =>
    {
        options.LoginPath = "/Account/Login";
        options.AccessDeniedPath = "/Account/AccessDenied";
        options.ExpireTimeSpan = TimeSpan.FromHours(8);
    });

// Configuração da Licença do QuestPDF
QuestPDF.Settings.License = QuestPDF.Infrastructure.LicenseType.Community;


// Configuração para proxy reverso (Render, Heroku, etc.)
builder.Services.Configure<ForwardedHeadersOptions>(options =>
{
    options.ForwardedHeaders = ForwardedHeaders.XForwardedFor | ForwardedHeaders.XForwardedProto;
    options.KnownNetworks.Clear();
    options.KnownProxies.Clear();
});

var app = builder.Build();

app.UseForwardedHeaders(); // Movido para o topo do pipeline

// === ADICIONADO: Auto-Migration para produção/Docker ===
// Garante que o banco de dados seja criado e atualizado automaticamente ao iniciar a aplicação.
using (var scope = app.Services.CreateScope())
{
    var services = scope.ServiceProvider;
    try
    {
        var context = services.GetRequiredService<AppDbContext>();
        // Cria as tabelas do banco automaticamente sem precisar da pasta Migrations
        context.Database.EnsureCreated();

        // Migração manual: Adiciona novas colunas caso o banco já tenha sido criado antes (pois o EnsureCreated não altera tabelas existentes)
        context.Database.ExecuteSqlRaw(@"
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""CustoPecas"" numeric NOT NULL DEFAULT 0;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""CustoMaoDeObra"" numeric NOT NULL DEFAULT 0;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""DescontoAplicado"" numeric NOT NULL DEFAULT 0;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""DataConclusao"" timestamp without time zone NULL;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""DataEntregaCliente"" timestamp without time zone NULL;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""AvariasPreExistentes"" text NULL;
            ALTER TABLE ""OrdensServico"" ADD COLUMN IF NOT EXISTS ""NumeroSerie"" text NULL;

            CREATE TABLE IF NOT EXISTS ""Pecas"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""Nome"" text NOT NULL,
                ""QuantidadeEstoque"" integer NOT NULL,
                ""ValorUnitario"" numeric NOT NULL
            );

            CREATE TABLE IF NOT EXISTS ""OrdemServicoPecas"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""OrdemServicoId"" integer NOT NULL REFERENCES ""OrdensServico"" (""Id"") ON DELETE CASCADE,
                ""PecaId"" integer NOT NULL REFERENCES ""Pecas"" (""Id"") ON DELETE CASCADE,
                ""Quantidade"" integer NOT NULL,
                ""ValorVenda"" numeric NOT NULL
            );

            CREATE TABLE IF NOT EXISTS ""Evidencias"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ""OrdemServicoId"" integer NOT NULL REFERENCES ""OrdensServico"" (""Id"") ON DELETE CASCADE,
                ""CaminhoArquivo"" text NOT NULL,
                ""DataUpload"" timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
        ");

        // Garante que a tabela de chaves de proteção exista, pois o EnsureCreated ignora se o banco já existir
        context.Database.ExecuteSqlRaw(@"
            CREATE TABLE IF NOT EXISTS ""DataProtectionKeys"" (
                ""Id"" integer GENERATED BY DEFAULT AS IDENTITY,
                ""FriendlyName"" text NULL,
                ""Xml"" text NULL,
                CONSTRAINT ""PK_DataProtectionKeys"" PRIMARY KEY (""Id"")
            );
        ");
    }
    catch (Exception ex)
    {
        var logger = services.GetRequiredService<ILogger<Program>>();
        logger.LogError(ex, "Ocorreu um erro ao aplicar as migrations do banco de dados.");
    }
}

// Configure the HTTP request pipeline.
if (!app.Environment.IsDevelopment())
{
    app.UseExceptionHandler("/Home/Error");
    app.UseHsts();
}


app.UseHttpsRedirection();
app.UseStaticFiles();

app.UseRouting();

// Middlewares de Segurança
app.UseAuthentication();
app.UseAuthorization();

app.MapControllerRoute(
    name: "default",
    pattern: "{controller=Home}/{action=Index}/{id?}");

app.Run();
